#undef TAPPING_TERM
#define TAPPING_TERM 150

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "Kylvl/v6AzJr"
#define LAYER_STATE_16BIT

#define RGB_MATRIX_STARTUP_SPD 60

